CREATE TABLE IF NOT EXISTS payment_notify_raw_logs (
  raw_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_name VARCHAR(50) NOT NULL DEFAULT 'received',
  controller VARCHAR(100) NOT NULL DEFAULT '',
  database_profile VARCHAR(50) NOT NULL DEFAULT '',
  request_method VARCHAR(16) NOT NULL DEFAULT '',
  request_url VARCHAR(500) NOT NULL DEFAULT '',
  request_path VARCHAR(255) NOT NULL DEFAULT '',
  request_ip VARCHAR(100) NOT NULL DEFAULT '',
  remote_address VARCHAR(100) NOT NULL DEFAULT '',
  content_type VARCHAR(255) NOT NULL DEFAULT '',
  user_agent VARCHAR(500) NOT NULL DEFAULT '',
  headers_json LONGTEXT NULL,
  query_json LONGTEXT NULL,
  params_json LONGTEXT NULL,
  body_type VARCHAR(50) NOT NULL DEFAULT '',
  body_json LONGTEXT NULL,
  raw_body LONGTEXT NULL,
  payload_json LONGTEXT NULL,
  normalized_json LONGTEXT NULL,
  error_message LONGTEXT NULL,
  error_stack LONGTEXT NULL,
  date_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (raw_id),
  KEY idx_date_create (date_create),
  KEY idx_controller (controller),
  KEY idx_event_name (event_name),
  KEY idx_database_profile (database_profile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
